" Essential for finding other files
if v:progname ==# 'vi' || v:progname ==# 'view'
    source $DOTFILES/vim/config/minimal.vim
    finish
endif
" Source configuration files in order
source $DOTFILES/vim/config/basic.vim
source $DOTFILES/vim/config/plugins.vim
source $DOTFILES/vim/config/plugins_config.vim
source $DOTFILES/vim/config/autopairs.vim
source $DOTFILES/vim/config/autocmds.vim
source $DOTFILES/vim/config/mappings.vim
source $DOTFILES/vim/config/python.vim
source $DOTFILES/vim/config/sql.vim
source $DOTFILES/vim/config/yaml.vim
source $DOTFILES/vim/config/json.vim
source $DOTFILES/vim/config/vimscript.vim
" Setup auto-reloading
augroup reload_vimrc
  autocmd!
  autocmd BufWritePost $DOTFILES/vim/vimrc,$DOTFILES/vim/config/*.vim source $DOTFILES/vim/vimrc
augroup END
