
" Essential for finding other files
" set runtimepath $HOME/.vim
" set runtimepath $HOME/.vim/after

" Source configuration files in order

source $HOME/.vim/config/basic.vim
source $HOME/.vim/config/plugins.vim
source $HOME/.vim/config/plugins_config.vim
source $HOME/.vim/config/autopairs.vim
source $HOME/.vim/config/autocmds.vim
source $HOME/.vim/config/mappings.vim
source $HOME/.vim/config/python.vim
source $HOME/.vim/config/sql.vim
source $HOME/.vim/config/yaml.vim
source $HOME/.vim/config/json.vim
source $HOME/.vim/config/vimscript.vim


" Setup auto-reloading
augroup reload_vimrc
  autocmd!
  autocmd BufWritePost ~/.vim/vimrc,~/.vim/config/*.vim source ~/.vim/vimrc
augroup END
