# Hardware Decoding & Video Driver
gpu-context=auto      # Let mpv decide the best context
gpu-api=opengl        # Stable backend for Integrated AMD
hwdec=vaapi           # Explicit AMD/Intel decoding
vo=gpu-next           # Modern renderer
profile=high-quality  # Enables high-quality scaling and debanding

# Motion Interpolation (Smooth video on 60Hz+ screens)
video-sync=display-resample
interpolation
tscale=oversample

# Languages
# Audio: Farsi, English, German, Italian, Portuguese, Spanish
alang=fa,per,en,eng,de,ger,it,ita,pt,por,es,spa
# Subtitles: English, Farsi, German, Italian
slang=en,eng,fa,per,de,ger,it,ita

# OSD & Fonts
# 'Noto Sans' is standard on Arch and handles Farsi/Latin mix well.
osd-font='Noto Sans'
osd-font-size=30
osd-border-size=2
osd-color='#CCFFFFFF' # Slightly transparent white
sub-font='Noto Sans'  # Apply to subtitles as well

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=7
screenshot-directory=~/Pictures/mpv

# Behavior
save-position-on-quit # Remember where you left off
keep-open=yes         # Don't close the player after the video ends
script=/usr/lib/mpv-mpris/mpris.so