# Hardware Decoding & Video Driver
gpu-context=auto      # Let mpv decide the best context
gpu-api=vulkan        # Best backend for RDNA3 + gpu-next
hwdec=vaapi           # Explicit AMD/Intel decoding
hwdec-codecs=all      # Apply VAAPI to all codecs (AV1, VP9, etc.)
vo=gpu-next           # Modern renderer
profile=high-quality  # Enables high-quality scaling and debanding

# Motion Interpolation (Smooth video on 60Hz+ screens)
video-sync=display-resample
interpolation
tscale=oversample

# Languages
# Audio: Farsi, English, German, Italian, Portuguese, Spanish
alang=fa,per,en,eng,de,ger,it,ita,pt,por,es,spa
# Subtitles: English, Farsi, German, Italian, Portuguese
slang=en,eng,fa,per,de,ger,it,ita,pt,por

# OSD & Fonts
# 'Noto Sans' is standard on Arch and handles Farsi/Latin mix well.
osd-font='Noto Sans'
osd-font-size=30
osd-border-size=2
osd-color='#CCFFFFFF' # Slightly transparent white
sub-font='Noto Sans'  # Apply to subtitles as well

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=7
screenshot-directory=~/Pictures/mpv

# Behavior
save-position-on-quit
keep-open=yes         # Don't close the player after the video ends
ytdl-format=bestvideo[height<=?1080][vcodec^=av01]+bestaudio[acodec=opus]/bestvideo[height<=?1080][vcodec^=vp9]+bestaudio[acodec=opus]/bestvideo[height<=?1080]+bestaudio/best
script-opts-append=ytdl_hook-ytdl_path=/home/farhad/.local/bin/yt-dlp-mpv
sub-auto=fuzzy        # Load subtitle files with similar names
volume-max=150