#!/bin/bash
case "$1" in
    volume-up)
        wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
        wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{v=int($2*100); print (v>100?100:v) " volume"}' > /tmp/wobpipe
        ;;
    volume-down)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
        wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100) " volume"}' > /tmp/wobpipe
        ;;
    volume-mute)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
        if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED; then
            echo "0 muted" > /tmp/wobpipe
        else
            wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100) " volume"}' > /tmp/wobpipe
        fi
        ;;
    brightness-up)
        brightnessctl set +5%
        echo "$(( $(brightnessctl get) * 100 / $(brightnessctl max) )) brightness" > /tmp/wobpipe
        ;;
    brightness-down)
        brightnessctl set 5%-
        echo "$(( $(brightnessctl get) * 100 / $(brightnessctl max) )) brightness" > /tmp/wobpipe
        ;;
esac
