#!/bin/bash

DB="${XDG_DATA_HOME:-$HOME/.local/share}/zathura/bookmarks.sqlite"

[[ -f "$DB" ]] || { notify-send "Zathura" "No history found."; exit 0; }

# Get history from DB, unique them, pipe to fuzzel
FILE=$(sqlite3 "$DB" "SELECT file FROM fileinfo ORDER BY time DESC" | fuzzel -d -p "🕒 History: " -w 120)

if [ -n "$FILE" ]; then
    setsid -f zathura "$FILE" >/dev/null 2>&1
fi
